import Head from 'next/head'
import Image from 'next/image'
import { getFeaturedEvents } from 'helpers/api-util'
import styles from '@/styles/Home.module.css'

import EventList from 'components/events/event-list'

export default function HomePage(props) {

  return (
    <>
      <Head>
        <title>ArcEvent</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      
      
             <EventList items={props.events}/>
       
   

      </div>
    </>
  )
}

export async function getStaticProps(){
  const featuredEvents = await getFeaturedEvents()
    return {
      props: {
          events:  featuredEvents
      },
      revalidate: 2000
    }
}