import Head from 'next/head'
import Image from 'next/image'

import styles from '@/styles/Home.module.css'
import { getFeaturedEvents } from 'dummy-data'
import EventList from 'components/events/event-list'

export default function HomePage() {
  const featuredEvents = getFeaturedEvents();
  return (
    <>
      <Head>
        <title>Next-me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      
      
             <EventList items={featuredEvents}/>
       
   

      </div>
    </>
  )
}
